"""
agents/tools/report_tools.py
-----------------------------
Tools for generating Allure reports and persisting run logs.
"""

import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).parent.parent.parent
ALLURE_RESULTS = ROOT / "allure-results"
ALLURE_REPORT = ROOT / "allure-report"
LOGS_DIR = ROOT / "agents" / "conversation-logs"


def generate_and_serve_report(
    port: int = 5050,
    open_browser: bool = True,
) -> dict:
    """
    Generate the Allure report from allure-results/ and serve it on localhost.

    Steps:
        1. allure generate allure-results/ --clean -o allure-report/
        2. allure serve allure-results/ --port {port}  (background process)

    Returns:
        {"url": str, "generated": bool, "serve_pid": int | None, "detail": str}
    """
    generated = False
    detail_parts = []

    # Step 1: generate static report
    gen_result = subprocess.run(
        ["allure", "generate", str(ALLURE_RESULTS), "--clean", "-o", str(ALLURE_REPORT)],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
    )
    if gen_result.returncode == 0:
        generated = True
        detail_parts.append(f"Report generated → {ALLURE_REPORT}/index.html")
    else:
        detail_parts.append(
            f"allure generate failed (returncode={gen_result.returncode}). "
            f"Is Allure CLI installed? (brew install allure)"
        )

    # Step 2: serve in background
    serve_pid = None
    url = f"http://localhost:{port}"
    try:
        proc = subprocess.Popen(
            ["allure", "serve", str(ALLURE_RESULTS), "--port", str(port)],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            cwd=str(ROOT),
        )
        serve_pid = proc.pid
        detail_parts.append(f"Serving at {url} (PID {serve_pid})")
    except FileNotFoundError:
        detail_parts.append("allure CLI not found — skipping serve. Install: brew install allure")
        url = f"file://{ALLURE_REPORT}/index.html"

    return {
        "url": url,
        "generated": generated,
        "serve_pid": serve_pid,
        "detail": " | ".join(detail_parts),
    }


def save_run_report(
    summary: str,
    results: dict,
    allure_url: str = "",
) -> dict:
    """
    Persist a structured run log to agents/conversation-logs/.

    Writes two files:
        run-{ISO_TIMESTAMP}.json  — machine-readable results
        run-{ISO_TIMESTAMP}.md   — human-readable narrative

    Args:
        summary:    Claude's natural-language narrative of the run
        results:    {"stages": {0: 0, 1: 0, ...}, "all_pass": bool, "duration": str}
        allure_url: URL where the Allure report is served

    Returns:
        {"saved_json": str, "saved_md": str}
    """
    LOGS_DIR.mkdir(parents=True, exist_ok=True)

    now = datetime.now(timezone.utc)
    ts_file = now.strftime("%Y-%m-%dT%H-%M")
    ts_display = now.strftime("%Y-%m-%d %H:%M UTC")

    # --- JSON ---
    json_path = LOGS_DIR / f"run-{ts_file}.json"
    json_data = {
        "run_at": now.isoformat(),
        "all_pass": results.get("all_pass", False),
        "duration": results.get("duration", "—"),
        "allure_url": allure_url,
        "stages": results.get("stages", {}),
        "summary": summary,
    }
    json_path.write_text(json.dumps(json_data, indent=2, default=str))

    # --- Markdown ---
    md_path = LOGS_DIR / f"run-{ts_file}.md"
    stage_labels = {
        0: "Env Check",
        1: "D3 Health Check",
        2: "Contract Tests",
        3: "API Suite",
        4: "D2 Mock Tests",
        5: "UI Suite",
        6: "D1 Visual",
    }
    stages = results.get("stages", {})
    overall = "ALL PASS ✓" if results.get("all_pass") else "FAILED ✗"

    rows = []
    for num, label in stage_labels.items():
        code = stages.get(num)
        if code is None:
            icon = "⏭ SKIP"
        elif code == 0:
            icon = "✓ PASS"
        else:
            icon = "✗ FAIL"
        rows.append(f"| {num} | {label} | {icon} |")

    stages_table = "\n".join(rows)
    allure_section = f"\n**Allure Report:** {allure_url}\n" if allure_url else ""

    md_content = f"""# ANYMUS QA Run — {ts_display}

**Result:** {overall}
**Duration:** {results.get("duration", "—")}
{allure_section}
## Stage Results

| Stage | Name | Status |
|-------|------|--------|
{stages_table}

## Narrative

{summary}

---
*Generated by ANYMUS QA Orchestration Agent (claude-sonnet-4-6)*
"""
    md_path.write_text(md_content)

    return {
        "saved_json": str(json_path),
        "saved_md": str(md_path),
    }


# ---------------------------------------------------------------------------
# Historical pattern detection
# ---------------------------------------------------------------------------

_STAGE_LABELS: dict[str, str] = {
    "0": "Env Check",
    "1": "D3 Health Check",
    "2": "Contract Tests",
    "3": "API Suite",
    "4": "D2 Mock Tests",
    "5": "UI Suite",
    "6": "D1 Visual",
}


def read_run_history(last_n: int = 5) -> dict[str, Any]:
    """
    Load the last N run logs from agents/conversation-logs/ and detect failure patterns.

    Classifies stages as "systemic" when they fail in ≥60 % of recent runs.
    Returns a pattern verdict that Claude can reason about before running new tests.

    Returns:
        {
          "runs_analyzed": int,
          "overall_pass_rate": float,          # 0.0 – 1.0
          "stage_failure_rates": {             # per-stage breakdown
              "3": {"label": "API Suite", "failures": 2, "runs": 5, "rate": 0.4}
          },
          "systemic_failures": ["API Suite"],  # stages with rate ≥ 0.6
          "pattern": str,                      # human-readable verdict
          "newest_run": str | None,
          "oldest_run": str | None,
        }
    """
    logs = sorted(LOGS_DIR.glob("run-*.json"), reverse=True)[:last_n]

    if not logs:
        return {
            "runs_analyzed": 0,
            "overall_pass_rate": None,
            "stage_failure_rates": {},
            "systemic_failures": [],
            "pattern": "No run history found — this appears to be the first run.",
            "newest_run": None,
            "oldest_run": None,
        }

    runs: list[dict] = []
    for p in logs:
        try:
            runs.append(json.loads(p.read_text()))
        except Exception:
            continue

    if not runs:
        return {
            "runs_analyzed": 0,
            "overall_pass_rate": None,
            "stage_failure_rates": {},
            "systemic_failures": [],
            "pattern": "Run log files found but could not be parsed.",
            "newest_run": None,
            "oldest_run": None,
        }

    # Tally per-stage failures
    stage_failures: dict[str, int] = {}
    stage_counts: dict[str, int] = {}

    for run in runs:
        for stage_key, code in (run.get("stages") or {}).items():
            key = str(stage_key)
            stage_counts[key] = stage_counts.get(key, 0) + 1
            if code not in (0, None):          # non-zero = failed
                stage_failures[key] = stage_failures.get(key, 0) + 1

    stage_failure_rates: dict[str, dict] = {}
    systemic_failures: list[str] = []

    for stage, total in stage_counts.items():
        fails = stage_failures.get(stage, 0)
        rate = fails / total
        label = _STAGE_LABELS.get(stage, f"Stage {stage}")
        stage_failure_rates[stage] = {
            "label": label,
            "failures": fails,
            "runs": total,
            "rate": round(rate, 2),
        }
        if rate >= 0.6:
            systemic_failures.append(label)

    overall_pass_rate = sum(1 for r in runs if r.get("all_pass")) / len(runs)

    # Build human-readable verdict
    if systemic_failures:
        pattern = (
            f"SYSTEMIC failures detected in: {', '.join(systemic_failures)}. "
            f"These stages have failed in ≥60% of the last {len(runs)} runs — "
            "this is not a flaky test, it is a persistent defect."
        )
    elif overall_pass_rate < 0.5:
        pattern = (
            f"Pipeline is UNSTABLE — only {overall_pass_rate:.0%} of the last "
            f"{len(runs)} runs passed. Multiple intermittent failures."
        )
    elif overall_pass_rate == 1.0:
        pattern = f"All {len(runs)} recent runs passed. Pipeline is stable."
    else:
        pattern = (
            f"Pipeline mostly stable ({overall_pass_rate:.0%} pass rate over "
            f"{len(runs)} runs). No systemic failures detected."
        )

    return {
        "runs_analyzed": len(runs),
        "overall_pass_rate": round(overall_pass_rate, 2),
        "stage_failure_rates": stage_failure_rates,
        "systemic_failures": systemic_failures,
        "pattern": pattern,
        "newest_run": runs[0].get("run_at"),
        "oldest_run": runs[-1].get("run_at"),
    }
